version: '3'

services:
  db:
    image: postgres:15-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 30s
      interval: 30s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      - pgdata:var/lib/postgresql/data 

volumes:
  pgdata: {}
