#!/bin/bash

cat >alice.yaml <<EOT
smtp:
  address: alice@mail.test
  password: alicepass
  host: localhost
  port: 25
  authenticated: false
  tls:
    enabled: false
imap:
  address: alice@mail.test
  password: alicepass
  host: localhost
  port: 993
  tls:
    insecure: true
EOT

cat >service.yaml <<EOT
timezone: America/Montreal
database:
  url: postgresql://mxremind:mxremind@localhost:5432/mxremind
mailbox:
  in: INBOX
  processed: Trash
smtp:
  address: reminders@mail.test
  password: reminderspass
  host: localhost
  port: 25
  authenticated: false
  tls:
    enabled: false
imap:
  address: reminders@mail.test
  password: reminderspass
  host: localhost
  port: 993
  tls:
    insecure: true
EOT
